### PR TITLE
Add a GitHub Actions configuration

### PR DESCRIPTION
**Pull request by sajith**
Addresses #30.  This should run tests against a few Python 3.x versions.

[Here](https://github.com/sajith/datamodel/actions/runs/2504194631) is an example of this at work where the tests fail; [here](https://github.com/sajith/datamodel/actions/runs/2498094521) is an example were tests pass.

Tests are currently failing, so this PR will be in draft status until the cause of those failures are addressed.  Problem seems to be with `tests/data/sdx.json`: I removed that file in PR #28 because it keeps mutating during each test run. It is not a good idea for a file in version control to mutate like that. 

Perhaps that file should be two different files: (1) an input file that doesn't mutate, and (2) an output file that mutates, something which git can safely ignore.  I do not understand the test suite well enough to know if this is a good idea.

### CODE REVIEW

**Comment by YufengXin** [comment]
I'll make the input test file non-mutable.

**Comment by YufengXin** [comment]
looks like the last PR fixed this.

**Comment by sajith** [comment]
@YufengXin This PR is work in progress. Please do not close yet. :-)

**Comment by sajith** [comment]
Seems to be working: please see https://github.com/sajith/datamodel/actions/runs/2505431503, for an example.  I believe they will show up in https://github.com/atlanticwave-sdx/datamodel/actions once this PR is merged.

@YufengXin Please take a look and merge if you feel like this is useful in the current shape.

**Pull request merged**
