### PR TITLE
Update datamodel topology files according to Spec 2.0.0

### PR DESCRIPTION
**Pull request by italovalcy**
This pull request updates the data model files according to Topology Data Model Specification 2.0.0 (https://docs.google.com/document/d/1lgxjIT144EFu1G_OVcU19hN1cSUT_v2-tE0Z-7UlkNg/edit).

### CODE REVIEW

**Comment by YufengXin** [comment]
We'll test and update the parser. Thx

**Comment by YufengXin** [comment]
self = <sdx_datamodel.parsing.servicehandler.ServiceHandler object at 0x7fe136c1c100>
data = ['l2vpn-ptp']

    def import_service_data(self, data) -> Service:
        try:
>           owner = data["owner"]
E           TypeError: list indices must be integers or slices, not str

**Comment by italovalcy** [comment]
> self = <sdx_datamodel.parsing.servicehandler.ServiceHandler object at 0x7fe136c1c100> data = ['l2vpn-ptp']
> 
> ```
> def import_service_data(self, data) -> Service:
>     try:
> ```
> 
>  > ```
> >       owner = data["owner"]
> > ```
> 
> E TypeError: list indices must be integers or slices, not str

Hi @YufengXin thanks a lot for your help on this pull request and for adjusting the parsing/unit tests. Very nice to have you as co-author of the PR. I will just wait for a review on the PR to proceed with the process.

**Review by congwang09 — APPROVED** [review]
LGMT!

**Pull request merged**
