### PR TITLE
Remove topologymanager module

### PR DESCRIPTION
**Pull request by sajith**
Issue is #79: this module is being moved to pce, in https://github.com/atlanticwave-sdx/pce/pull/98.

### CODE REVIEW

**Comment by sajith** [comment]
The drop in coverage is due to honesty :-)

Previously reported coverage was measuring coverage of tests (see https://coveralls.io/builds/55212972), which is meaningless. With some changes in `setup.cfg` in this branch, now we're measuring actual test coverage of the library.

**Comment by YufengXin** [comment]
where does it (topologymanger) go?-:) is it ready to use in pre? thanks

**Comment by sajith** [comment]
> where does it (topologymanger) go?-:) is it ready to use in pre? thanks

It was moved to pce, in https://github.com/atlanticwave-sdx/pce/pull/96, and I'm making some more changes in https://github.com/atlanticwave-sdx/pce/pull/98 (mainly error handling and some refactoring).

So sdx-controller will use `sdx.pce.topology` instead of `sdx.datamodel.topologymanager`, and that change is being done in https://github.com/atlanticwave-sdx/sdx-controller/pull/119.   I think these changes are pretty much close to ready, modulo bugs and some more possible refactoring, of course.  But we can remove this code now from pce, because sdx-controller's main branch is set to use datamodel tagged 1.0.0a, so it will continue to work.

The reason for this set of changes is stated in https://github.com/atlanticwave-sdx/pce/issues/95.  Basically, some classes were added to represent connection requests and solutions in pce (instead of plain old arrays and dicts), and topology-related classes can share that code easily if we move them to pce.

**Comment by YufengXin** [comment]
Thanks. I asked because I need to add some code to take care of the vlan reservation for every path. They're mostly done in my own branch. I will find the right place to add.

**Review by YufengXin — APPROVED** [review]

**Pull request merged**
