### PR TITLE
Validate and document schemas

### LINKED ISSUE #105: Update, validate, and document JSON schemas
- Make sure that schema files can be used to validate the JSON files in test data directory.
- Add some notes in README about the schema files.

Related to #92.

### PR DESCRIPTION
**Pull request by sajith**
Fixes #105.  Changes:

- Adds some tests to validate component descriptions (topology, node, port,..)  against their corresponding schemas.
- Updates the schemas so that `$ref` values refer to the correct external files, and other things that surfaced when testing.
- Formats the schemas using `python3 -m json.tool <infile> <outfile`.  I just like mechanically formatted files. ;-)

### CODE REVIEW

**Comment by sajith** [comment]
This appears to be the way to validate a given JSON blob against a schema with Python:

```python
import json
import pathlib

import jsonschema
import jsonref    # to expand `$ref`

blob = json.loads(pathlib.Path("port-data.json").read_text())
schema_file = pathlib.Path("port-schema.json")
schema = jsonref.loads(schema_file.read_text(), base_uri = schema_file.absolute().as_uri())

jsonschema.validate(blob, schema)
```

With some changes (correct `$ref` etc), most of the test data files validate against the schemas we have, except for this little annoying `vendor` thing:

https://github.com/atlanticwave-sdx/datamodel/blob/2548a8edaf09843e647e2291d9eac9912bf7d0bf/schemas/Service.json#L15-L24

Perhaps that could be removed?  The draft Data Model 2.0.0 spec has no mention of a `vendor` field.

**Comment by YufengXin** [comment]
Tthis can be commented out for now. Noticing the 'not' key, it was asked by FIU to be able to exclude certain vendor's equipments for security reasons.

**Comment by sajith** [comment]
Sadly JSON do not have "real" comment syntax.  And it is the `not` that makes validator unhappy:

```
jsonschema.exceptions.SchemaError: [{'type': 'array', 'items': [{'type': 'string'}]}] is not of type 'object', 'boolean'
```

I'm guessing it should be `"not": { "anyOf" : [...] }"` -- that `anyOf` should give `not` the boolean it needs.

**Comment by YufengXin** [comment]
Yes, this should work: "not": { "anyOf" : [...] }"

**Comment by YufengXin** [comment]
This tool is cool. I guess it's relatively new. I googled around and didn't find such a tool two years ago!

**Review by YufengXin — APPROVED** [review]

**Pull request merged**
